### ISSUE TITLE
Unknown client when attempting to sign in

### ISSUE THREAD

**Issue by juliettebee** [tidal-music/tidal-sdk-ios#33]
Hello,
I have two questions. I'm trying to sign in, here's my code: 
```swift
        let credentialsKey = "????"
        let clientId = "from developer.tidal.com"
        let clientSecret = "from developer.tidal.com"
        
        
        let authConfig = AuthConfig(
            clientId: clientId,
            clientSecret: clientSecret,
            credentialsKey: credentialsKey
        )
        
        let auth = TidalAuth.shared
        
        let loginConfig = LoginConfig()
        let redirectUri = "https://juliette.page/tidal"
        
        guard let loginURL = auth.initializeLogin(redirectUri: redirectUri, loginConfig: loginConfig) else {
            print("Something is wrong")
            return
        }
        print(loginURL)
        
        TidalAuth.shared.config(config: authConfig)
        url = loginURL
```

My first question is where do I get my credentials key? I've looked around in the Tidal developer dashboard and can't find anything and the documentation isn't specific on what to put. Along with that when I attempt to sign in I get the error "Unknown client: waves" printed in the console. I have "waves" as the client name in the Tidal developer dashboard. Is there anything I can do or am I not supposed to be using this SDK? 

Thank you have a good night!

**Comment by e-kononenko** [comment]
Hi @juliettebee, thank you for your question!

Please try to call `TidalAuth.shared.config(config: authConfig)` before initializing login.

As for `credentialsKey` - it is just the key used to store credentials in the system keychain. In our [example](https://github.com/tidal-music/tidal-sdk-ios/blob/e76cca392e7891a93fea6f8cf13d4a4610837790/TestApps/Auth/AuthTestApp/AuthViewModel.swift#L28) we use `storage`, but feel free to pick any unique name you like.

Let us know if it helps!

**Comment by juliettebee** [comment]
Thank you so much! Got it working!
